name: Build

on: 
  push:
    branches: 
      - 'dev1'
    paths: 
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the App
        run: |
          echo "Hello World!"
          echo "${{ vars.MYVARIABLE }}"
