name: Build

on: 
  push:
    branches: 
      - 'dev1'
    paths: 
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the App
        run: |
          echo "building the App D-v${{ github.run_number }}"
          echo "${{ vars.MYVARIABLE }}"
  
  # tagthebuild:
  #   needs: build
  #   if: github.ref == 'refs/heads/dev1'
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}

  #   steps: 
  #     - name: Check out the repository
  #       uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Configure Git with GitHub token
  #       run: |
  #         # git config --global user.email "actions@github.com"
  #         git config --global user.name "${{ github.actor }}"
  #         git remote set-url origin "https://github.com/${{ github.repository }}"

  #     - name: Create tag
  #       run: |
  #         git tag -a D-v${{ github.run_number }} -m "Dev Release v${{ github.run_number }}"
  #         git push --tags
