name: Deploy

on: 
  # create:
  workflow_run:
    workflows: [Test]
    types:
      - completed
  workflow_dispatch:

env:
  tagtodeploy: ${{ vars.LAST_TAG_VERSION }}
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy App
        run: |
          echo "Reference : ${{ github.ref }}"
          echo "Reference Type : ${{ github.ref_type }}"
          echo "Deploying App with tag ${{ env.tagtodeploy }}"
          echo "${{vars.MYVARIABLE}}"
