name: Deploy

on: 
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo "Hello World"
          echo "${{vars.MYVARIABLE}}"
