name: Test

on: 
  # pull_request:
  #   types:
  #     - closed
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    name: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          echo "Hello World!"
          echo "${{ vars.MYVARIABLE }}"
  
  tagthebuild:
    needs: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}

    steps: 
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/S-v${{ github.run_number }}',
      #         sha: context.sha
      #       })
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          git tag -a S-v${{ github.run_number }} -m "Stage Release v${{ github.run_number }}"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}