name: Test

on: 
 push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    name: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          echo "Hello World!"
          echo "${{ vars.MYVARIABLE }}"
  
  tagthebuild:
    needs: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}

    steps: 
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git with GitHub token
        run: |
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin "https://github.com/${{ github.repository }}"

      - name: Create tag
        run: |
          git tag -a S-v${{ github.run_number }} -m "Stage Release v${{ github.run_number }}"
          git push --tags