name: Test

on: 
 push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  testing:
    name: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          echo "Hello World!"
          echo "${{ vars.MYVARIABLE }}"
  
  
  tagthebuild:
    needs: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}

    steps: 
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git with GitHub token
        run: |
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin "https://github.com/${{ github.repository }}"

      - name: Create tag
        id: create-tag
        run: |
          git tag -a S-v${{ github.run_number }} -m "Stage Release v${{ github.run_number }}"
          git push --tags

      - name: Set Environment variable with created Tag
        if: steps.create-tag.outcome == 'success'
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME:  ${{ github.repository }}
          VARIABLE_NAME: LAST_TAG_VERSION
          VARIABLE_VALUE: D-v${{ github.run_number }}
          PAT_TOKEN: ${{ secrets.REPO_VAR_REST_API_TOKEN }}
        run: |
          # echo "REPO OWNER : ${{ env.REPO_OWNER }}"
          # echo "REPO NAME : ${{ env.REPO_NAME }}"
          # echo "VARIABLE NAME : ${{ env.VARIABLE_NAME }}"
          # echo "VARIABLE VALUE : ${{ env.VARIABLE_VALUE}}"
          # echo "PAT TOKEN : ${{ env.PAT_TOKEN }}"
          # echo "URL: https://api.github.com/repos/${{ env.REPO_NAME }}/actions/variables/${{ env.VARIABLE_NAME }}"

          # curl -X GET \
          #   -H "Authorization: Bearer ${{ env.PAT_TOKEN }}" \
          #   "https://api.github.com/user"
            
          # curl -L \
          #   -H "Accept: application/vnd.github+json" \
          #   -H "Authorization: Bearer ${{ env.PAT_TOKEN }}" \
          #   -H "X-GitHub-Api-Version: 2022-11-28" \
          #   https://api.github.com/repos/${{ env.REPO_NAME }}/actions/variables/${{ env.VARIABLE_NAME }}
          
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.REPO_NAME }}/actions/variables/${{ env.VARIABLE_NAME }} \
            -d '{"name":"${{ env.VARIABLE_NAME }}","value":"${{ env.VARIABLE_VALUE}}"}'

          echo "VARIABLE VALUE : ${{ vars.LAST_TAG_VERSION }}"