name: Test

on: 
  # pull_request:
  #   types:
  #     - closed
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Stage' || 'Dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo "Hello World!"
          echo "${{ vars.MYVARIABLE }}"

